### ISSUE TITLE
Modify meta tag formatting in seehuhn.de

### ISSUE THREAD

**Issue by shaqque** [seehuhn/go-websocket#1]
Per golang/go#38205, the current meta tag at https://www.seehuhn.de/go/websocket?go-get=1 displays

```
<meta name="go-import" content="seehuhn.de/go/websocket git https://github.com/seehuhn/go-websocket.git">
```

but should instead show

```
<meta name="go-import" content="seehuhn.de/go/websocket git https://github.com/seehuhn/go-websocket">
```

following the formatting guide from `go help importpath`. The extra ".git" qualifier causes the links in https://pkg.go.dev/seehuhn.de/go/websocket?tab=doc to point to the wrong repo URL.

**Comment by seehuhn** [comment]
This is now fixed.
